<?php
/**
 * @file
 */

include_once('gsb_feature_wysiwyg.features.inc');
include_once('gsb_feature_wysiwyg.features.wysiwyg.inc');

/**
 * Implements hook_apps_app_info()
 */
function gsb_feature_wysiwyg_apps_app_info() {
  return array(
    'configure form' => 'gsb_feature_wysiwyg_configure_form',
  );
}

/**
 * Implement hook_permission.
 */
function gsb_feature_wysiwyg_permission() {
  return array(
    'choose text format' => array(
      'title' => t('Choose text format'),
      'description' => t('Allow the user to choose a text format in text areas.'),
    ),
  );
}

/**
 * Configuration Form for GSB WYSIWYG
 */
function gsb_feature_wysiwyg_configure_form($form, &$form_state) {
  $form = array();

  $form['gsb_feature_wysiwyg_show_format_details'] = array(
    '#title' => t('Show Text Formatter Details'),
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => array(
      '1' => 'Show',
      '0' => 'Do Not Show',
    ),
    '#default_value' => variable_get('gsb_feature_wysiwyg_show_format_details', 0),
    '#description' => t('Do you want gsb to show the help text and text format guidelines?'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function gsb_feature_wysiwyg_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
  * Implementation of hook_wysiwyg_plugin().
  */
function gsb_feature_wysiwyg_wysiwyg_plugin($editor) {
  switch ($editor) {
    case 'tinymce':
      return array(
        'pdw' => array(
          'path' => drupal_get_path('module', 'gsb_feature_wysiwyg') . '/plugins/wysiwyg/pdw',
          'filename' => 'editor_plugin.js',
          'buttons' => array(
            'pdw_toggle' => t('Kitchen Sink')
          ),
          'url' => 'http://www.neele.name/pdw_toggle_toolbars/',
          'load' => TRUE,
        ),
        'spellchecker' => array(
          'internal' => TRUE,
          'buttons' => array(
            'spellchecker' => t('Spell Check')
          ),
          'url' => 'http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/spellchecker',
          'load' => TRUE,
        ),
        'inlinepopups' => array(
          'internal' => TRUE,
          'url' => 'http://www.tinymce.com/wiki.php/Plugin:inlinepopups',
          'load' => TRUE,
        ),
      );
  }
}


/**
 * Implements of hook_element_info_alter().
 */
function gsb_feature_wysiwyg_element_info_alter(&$type) {
  // Change text format processing on elements to our version.
  if (isset($type['text_format'])) {
    $type['text_format']['#process'][] = 'gsb_feature_wysiwyg_filter_process_format';
  }
}

/**
 * Callback for processing the text_format element
 */
function gsb_feature_wysiwyg_filter_process_format($element) {

  // Do not auto submit the form due to changes of the filter
  $element['format']['format']['#attributes']['class'][] = 'ctools-auto-submit-exclude';

  // Do not show the guidelines and help text for text formatters
  // Also format this all a bit different so that it looks right
  if (!variable_get('gsb_feature_wysiwyg_show_format_details', FALSE)) {
    $element['format']['#weight'] = 1;

    // Start building our classes for the wrapper.
    $classes[] = 'format-toggle';

    // We need to use css to hide the format chooser because wysiwyg module
    // doesn't work if #access = FALSE.
    if (!user_access('choose text format')) {
      $classes[] = 'element-hidden';
    }
    $element['format']['#prefix'] = '<div class="' . implode(' ', $classes) . '">';
    $element['format']['#suffix'] = '</div><div class="clearfix"></div>';
    unset($element['format']['#type']);
    $element['format']['format']['#title'] = 'Editor: ';
    $element['format']['help']['#access'] = FALSE;
    $element['format']['guidelines']['#access'] = FALSE;
  }

  return $element;
}

/**
 * Implementation of hook_module_implements_alter()
 */
function gsb_feature_wysiwyg_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'wysiwyg_editor_settings_alter') {
    $group = $implementations['gsb_feature_wysiwyg'];
    unset($implementations['gsb_feature_wysiwyg']);
    $implementations['gsb_feature_wysiwyg'] = $group;
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter()
 */
function gsb_feature_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {

  // If there is a toolbar, then arrange the buttons in a specific order
  if (isset($settings['toolbar'][0])) {

    unset($settings['toolbar'][0]);

    $button_defaults = array(
      "Bold",
      "Italic",
      "Styles",
      "JustifyLeft",
      "JustifyCenter",
      "JustifyRight",
      "-",
      "BulletedList",
      "NumberedList",
      "-",
      "Undo",
      "Redo",
      "-",
      "Link",
      "Unlink",
      "Anchor",
      "linkit",
      "-",
      "Image",
      "Superscript",
      "Blockquote",
      "SpecialChar",
      "Source",
      "HorizontalRule",
      "-",
      "Cut",
      "Copy",
      "PasteText",
      "PasteFromWord",
      "-",
      "Table",
      "SelectAll",
      "SpellChecker",
      "Scayt",
      "media"
    );

    // Get the current settings for the buttons (the enabled buttons)
    $current_settings = array();
    foreach($context['profile']->settings['buttons'] as $buttons) {
      $current_settings = array_merge($current_settings, array_keys($buttons));
    }

    // Remove any buttons that are not enabled
    foreach ($button_defaults as $key => $button) {
      if ($button != '-' && !in_array($button, $current_settings)) {
        unset($button_defaults[$key]);
      }
    }

    // Remove any separators that have no items between them
    $last_is_separator = FALSE;
    foreach ($button_defaults as $key => $button) {
      if ($button == '-') {
        if ($last_is_separator) {
          unset($button_defaults[$key]);
        }
        $last_is_separator = TRUE;
      }
      else {
        $last_is_separator = FALSE;
      }
    }

    $button_defaults = array_values($button_defaults);

    // If we have a separator as the first item, then remove it
    if ($button_defaults[0] == '-') {
      unset($button_defaults[0]);
    }
    // If we have a separator as the last item, then remove it
    if ($button_defaults[count($button_defaults)-1] == '-') {
      unset($button_defaults[count($button_defaults)-1]);
    }

    $settings['toolbar'][0] = array_values($button_defaults);

  }

  // Enable Spell check as you type automatically.
  $settings['scayt_autoStartup'] = TRUE;

  // stop ckeditor from encoding
  // example - the text what's was being changed
  // from what's to what&#39;s
  // adding this setting stopped this encoding.
  $settings['entities'] = FALSE;

  // Stop ckeditor from stripping out content.
  if ($context['profile']->editor == 'ckeditor') {
    $settings['allowedContent'] = TRUE;
  }
}

/**
 * Implements hook_filter_info().
 */
function gsb_feature_wysiwyg_filter_info() {

  $filters['gsb_filter_strip'] = array(
    'title' =>  t('GSB Filter - Strip non-blank-space paragraphs'),
    'process callback' => '_gsb_feature_wysiwyg_filter_strip',
    'weight' => 10,
  );

  return $filters;

}

/**
 * Filter string paragraphs with &nbsp; and whitespaces only.
 * Examples:
 *  "<p>&nbsp;</p>", "<p>&nbsp; </p>", "<p> </p>"
 */
function _gsb_feature_wysiwyg_filter_strip($text) {
  return preg_replace('~<p>[\x{00a0}|\s]*</p>~siu', '', $text);
}

